<template>
  <h1>{{ message }}</h1>
  <p>
    Powered by <a href="https://v3.vuejs.org/">Vue 3</a>, generated by
    <a href="https://tridiamond.gitbook.io/diamond">Diamond</a>.
  </p>
  <h3>Installed CLI Plugins</h3>
  <ul>
    <li>
      <a
        href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-babel"
        target="_blank"
        rel="noopener"
      >
        babel
      </a>
    </li>
    <li>
      <a
        href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-router"
        target="_blank"
        rel="noopener"
      >
        router
      </a>
    </li>
    <li>
      <a
        href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-vuex"
        target="_blank"
        rel="noopener"
      >
        vuex
      </a>
    </li>
    <li>
      <a
        href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-eslint"
        target="_blank"
        rel="noopener"
      >
        eslint
      </a>
    </li>
    <li>
      <a
        href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-unit-mocha"
        target="_blank"
        rel="noopener"
      >
        unit-mocha
      </a>
    </li>
  </ul>
  <h3>Essential Links</h3>
  <ul>
    <li>
      <a href="https://vuejs.org" target="_blank" rel="noopener">Core Docs</a>
    </li>
    <li>
      <a href="https://forum.vuejs.org" target="_blank" rel="noopener">
        Forum
      </a>
    </li>
    <li>
      <a href="https://chat.vuejs.org" target="_blank" rel="noopener">
        Community Chat
      </a>
    </li>
    <li>
      <a href="https://twitter.com/vuejs" target="_blank" rel="noopener">
        Twitter
      </a>
    </li>
    <li>
      <a href="https://news.vuejs.org" target="_blank" rel="noopener">News</a>
    </li>
  </ul>
  <h3>Ecosystem</h3>
  <ul>
    <li>
      <a href="https://router.vuejs.org" target="_blank" rel="noopener">
        vue-router
      </a>
    </li>
    <li>
      <a href="https://vuex.vuejs.org" target="_blank" rel="noopener">vuex</a>
    </li>
    <li>
      <a
        href="https://github.com/vuejs/vue-devtools#vue-devtools"
        target="_blank"
        rel="noopener"
      >
        vue-devtools
      </a>
    </li>
    <li>
      <a href="https://vue-loader.vuejs.org" target="_blank" rel="noopener">
        vue-loader
      </a>
    </li>
    <li>
      <a
        href="https://github.com/vuejs/awesome-vue"
        target="_blank"
        rel="noopener"
      >
        awesome-vue
      </a>
    </li>
  </ul>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'

export default defineComponent({
  name: 'Diamond',
  props: {
    msg: String
  },
  setup(props) {
    const message = ref(props.msg)
    return { message }
  }
})
</script>

<style lang="scss" scoped>
a {
  color: #fff;
  position: relative;
  text-decoration: none;
  z-index: 1;
}
a:after {
  content: '';
  position: absolute;
  z-index: -1;
  top: 60%;
  left: -0.1em;
  right: -0.1em;
  bottom: 0;
  transition: top 200ms cubic-bezier(0, 0.8, 0.13, 1);
  background-color: rgba(123, 238, 252, 0.35);
}
a:hover:after {
  top: 0;
}
p {
  font-weight: bold;
  font-size: 18px;
}
h3 {
  margin: 40px 0 0;
  padding-bottom: 10px;
  border-bottom: 1px solid;
  border-width: 1px;
  border-image-slice: 1;
  border-image-source: linear-gradient(
    to right,
    #100e17,
    #100e17,
    #100e17,
    rgba(244, 86, 157, 1),
    #100e17,
    #100e17,
    #100e17
  );
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  font-size: 18px;
  display: inline-block;
  margin: 0 10px;
}
</style>
